version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y nginx
      
  build:
    commands:
      - echo "Building the typing game..."
      - echo "Running tests..."
      # Add your testing commands here
      - echo "Tests completed successfully!"
      
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://$S3_BUCKET/ --exclude ".git/*" --exclude "buildspec.yml" --delete
      - echo "Creating CloudFront cache invalidation..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: .
